export const data = [
  {
    siteName: "Yandex",
    icon: "./images/yandex-icon.png",
    type: "images",
    url: "https://",
    checked: true,
    id: 0,
  },
  {
    siteName: "DuckDuckGo",
    icon: "./images/DuckDuckGo-icon.png",
    type: "images",
    url: "https://",
    checked: true,
    id: 1,
  },
  {
    siteName: "Google",
    icon: "./images/Google-icon.png",
    type: "images",
    url: "https://",
    checked: true,
    id: 2,
  },
  {
    siteName: "Pixabay",
    icon: "./images/Pixabay-icon.png",
    type: "photos",
    url: "https://",
    checked: false,
    id: 3,
  },
  {
    siteName: "Pixels",
    icon: "./images/Pixels-icon.png",
    type: "photos",
    url: "https://",
    checked: false,
    id: 4,
  },
  {
    siteName: "Unsplash",
    icon: "./images/Unsplash-icon.png",
    type: "photos",
    url: "https://",
    checked: false,
    id: 5,
  },
  {
    siteName: "Pixabay",
    icon: "./images/Pixabay-icon.png",
    type: "videos",
    url: "https://",
    checked: false,
    id: 6,
  },
  {
    siteName: "Pixels",
    icon: "./images/Pixels-icon.png",
    type: "videos",
    url: "https://",
    checked: false,
    id: 7,
  },
];
